language: node_js

node_js:
  - "0.12"
  - "4"
  - "5"

env:
  - WEBPACK_VERSION=1
  - WEBPACK_VERSION=beta

before_script:
  - "npm install webpack@$WEBPACK_VERSION"

script:
  - if [ "${TRAVIS_NODE_VERSION}" != "0.12" ]; then npm run lint; fi
  - npm run test
