language: node_js

node_js:
  - "0.12"
  - "4"
  - "5"

env:
  - WEBPACK_VERSION=1
  - WEBPACK_VERSION=beta

before_script:
  - "npm install webpack@$WEBPACK_VERSION"

script:
  - npm run lint
  - npm run test
